install:
 - ps: $url = "https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/zip/elasticsearch/2.4.0/elasticsearch-2.4.0.zip"
 - ps: $output = "c:\Windows\temp\es.zip"
 - ps: Invoke-WebRequest -Uri $url -OutFile $output
 - ps: New-Item -ItemType 'Directory' -Path 'c:\Elasticsearch' -Force
 - ps: 7z x C:\Windows\Temp\es.zip -oC:\Elasticsearch
 - ps: $env:JAVA_HOME = 'C:\Program Files\Java\jdk1.8.0'
 - ps: Start-Process -FilePath 'C:\Elasticsearch\elasticsearch-2.4.0\bin\elasticsearch.bat' -WorkingDirectory 'c:\Elasticsearch\elasticsearch-2.4.0\bin'
 - ps: Start-Sleep -s 5
build_script:
  - build.cmd build